ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ENV NIX_CONFIG="experimental-features = nix-command flakes"

RUN nix-channel --update

ARG APP_DIR=/workspace
WORKDIR ${APP_DIR}
COPY flake.* ${APP_DIR}

RUN nix develop --command true
